FROM ubuntu:18.04
ENTRYPOINT [ "sleep" ]  # `Executable` command
# CMD [ "sleep", "4" ] <= JSON format Array
# CMD sleep 3 <= Shell format
CMD ["7"] # `Default Argument`

# What is the difference between CMD and ENTRYPOINT ?
# CMD is Overridable